### ISSUE TITLE
Readability

### ISSUE THREAD

**Issue by asheelamagwili** [kippyan/DataScience#2]
https://github.com/kippyan/DataScience/blob/45b275e2d93d0be6babd96b39774371f44674af8/P01.Rmd#L54

Using markup tools can make the knitted version of this easier to read. The source code is very well formatted and documented but when knitted to HTML the tabs and spaces don't appear in the browser resulting in plain paragraph.

**Comment by recursory** [comment]
I resolved this issue by using bullets and indentation with R markdown syntax.
